// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CallResponseDirection.
const (
	Inbound  CallResponseDirection = "inbound"
	Outbound CallResponseDirection = "outbound"
)

// Valid indicates whether the value is a known member of the CallResponseDirection enum.
func (e CallResponseDirection) Valid() bool {
	switch e {
	case Inbound:
		return true
	case Outbound:
		return true
	default:
		return false
	}
}

// Defines values for CallResponseStatus.
const (
	CallResponseStatusBusy       CallResponseStatus = "busy"
	CallResponseStatusCanceled   CallResponseStatus = "canceled"
	CallResponseStatusCompleted  CallResponseStatus = "completed"
	CallResponseStatusDialing    CallResponseStatus = "dialing"
	CallResponseStatusFailed     CallResponseStatus = "failed"
	CallResponseStatusInProgress CallResponseStatus = "in_progress"
	CallResponseStatusNoAnswer   CallResponseStatus = "no_answer"
	CallResponseStatusQueued     CallResponseStatus = "queued"
	CallResponseStatusRinging    CallResponseStatus = "ringing"
)

// Valid indicates whether the value is a known member of the CallResponseStatus enum.
func (e CallResponseStatus) Valid() bool {
	switch e {
	case CallResponseStatusBusy:
		return true
	case CallResponseStatusCanceled:
		return true
	case CallResponseStatusCompleted:
		return true
	case CallResponseStatusDialing:
		return true
	case CallResponseStatusFailed:
		return true
	case CallResponseStatusInProgress:
		return true
	case CallResponseStatusNoAnswer:
		return true
	case CallResponseStatusQueued:
		return true
	case CallResponseStatusRinging:
		return true
	default:
		return false
	}
}

// Defines values for EventStreamResponseCallStatus.
const (
	EventStreamResponseCallStatusBusy       EventStreamResponseCallStatus = "busy"
	EventStreamResponseCallStatusCanceled   EventStreamResponseCallStatus = "canceled"
	EventStreamResponseCallStatusCompleted  EventStreamResponseCallStatus = "completed"
	EventStreamResponseCallStatusDialing    EventStreamResponseCallStatus = "dialing"
	EventStreamResponseCallStatusFailed     EventStreamResponseCallStatus = "failed"
	EventStreamResponseCallStatusInProgress EventStreamResponseCallStatus = "in_progress"
	EventStreamResponseCallStatusNoAnswer   EventStreamResponseCallStatus = "no_answer"
	EventStreamResponseCallStatusQueued     EventStreamResponseCallStatus = "queued"
	EventStreamResponseCallStatusRinging    EventStreamResponseCallStatus = "ringing"
)

// Valid indicates whether the value is a known member of the EventStreamResponseCallStatus enum.
func (e EventStreamResponseCallStatus) Valid() bool {
	switch e {
	case EventStreamResponseCallStatusBusy:
		return true
	case EventStreamResponseCallStatusCanceled:
		return true
	case EventStreamResponseCallStatusCompleted:
		return true
	case EventStreamResponseCallStatusDialing:
		return true
	case EventStreamResponseCallStatusFailed:
		return true
	case EventStreamResponseCallStatusInProgress:
		return true
	case EventStreamResponseCallStatusNoAnswer:
		return true
	case EventStreamResponseCallStatusQueued:
		return true
	case EventStreamResponseCallStatusRinging:
		return true
	default:
		return false
	}
}

// Defines values for ListCallsCallsGetParamsStatus.
const (
	Busy       ListCallsCallsGetParamsStatus = "busy"
	Canceled   ListCallsCallsGetParamsStatus = "canceled"
	Completed  ListCallsCallsGetParamsStatus = "completed"
	Dialing    ListCallsCallsGetParamsStatus = "dialing"
	Failed     ListCallsCallsGetParamsStatus = "failed"
	InProgress ListCallsCallsGetParamsStatus = "in_progress"
	NoAnswer   ListCallsCallsGetParamsStatus = "no_answer"
	Queued     ListCallsCallsGetParamsStatus = "queued"
	Ringing    ListCallsCallsGetParamsStatus = "ringing"
)

// Valid indicates whether the value is a known member of the ListCallsCallsGetParamsStatus enum.
func (e ListCallsCallsGetParamsStatus) Valid() bool {
	switch e {
	case Busy:
		return true
	case Canceled:
		return true
	case Completed:
		return true
	case Dialing:
		return true
	case Failed:
		return true
	case InProgress:
		return true
	case NoAnswer:
		return true
	case Queued:
		return true
	case Ringing:
		return true
	default:
		return false
	}
}

// CallCreate defines model for CallCreate.
type CallCreate struct {
	ConversationId *openapi_types.UUID     `json:"conversation_id,omitempty"`
	FirstMessage   *string                 `json:"first_message,omitempty"`
	From           *string                 `json:"from,omitempty"`
	Llm            *LLMConfig              `json:"llm,omitempty"`
	Metadata       *map[string]interface{} `json:"metadata,omitempty"`
	SystemPrompt   *string                 `json:"system_prompt,omitempty"`
	To             string                  `json:"to"`
	VoiceConfig    *VoiceConfig            `json:"voice_config,omitempty"`
}

// CallEventResponse defines model for CallEventResponse.
type CallEventResponse struct {
	CallId     openapi_types.UUID     `json:"call_id"`
	Id         openapi_types.UUID     `json:"id"`
	Kind       string                 `json:"kind"`
	OccurredAt time.Time              `json:"occurred_at"`
	Payload    map[string]interface{} `json:"payload"`
}

// CallListResponse defines model for CallListResponse.
type CallListResponse struct {
	Items      []CallResponse `json:"items"`
	NextCursor *string        `json:"next_cursor,omitempty"`
}

// CallResponse defines model for CallResponse.
type CallResponse struct {
	AnsweredAt      *time.Time            `json:"answered_at"`
	ConversationId  *openapi_types.UUID   `json:"conversation_id"`
	Direction       CallResponseDirection `json:"direction"`
	EndReason       *string               `json:"end_reason"`
	EndedAt         *time.Time            `json:"ended_at"`
	FromE164        string                `json:"from_e164"`
	Id              openapi_types.UUID    `json:"id"`
	InitialPrompt   *string               `json:"initial_prompt"`
	LivekitRoom     *string               `json:"livekit_room"`
	OrganizationId  openapi_types.UUID    `json:"organization_id"`
	ProviderCallSid *string               `json:"provider_call_sid"`
	RecordingS3Key  *string               `json:"recording_s3_key"`
	RequestedAt     time.Time             `json:"requested_at"`
	StartedAt       *time.Time            `json:"started_at"`
	Status          CallResponseStatus    `json:"status"`
	ToE164          string                `json:"to_e164"`
}

// CallResponseDirection defines model for CallResponse.Direction.
type CallResponseDirection string

// CallResponseStatus defines model for CallResponse.Status.
type CallResponseStatus string

// EventStreamResponse defines model for EventStreamResponse.
type EventStreamResponse struct {
	CallStatus *EventStreamResponseCallStatus `json:"call_status,omitempty"`
	Items      []CallEventResponse            `json:"items"`
	NextCursor *string                        `json:"next_cursor,omitempty"`
}

// EventStreamResponseCallStatus defines model for EventStreamResponse.CallStatus.
type EventStreamResponseCallStatus string

// HTTPValidationError defines model for HTTPValidationError.
type HTTPValidationError struct {
	Detail *[]ValidationError `json:"detail,omitempty"`
}

// LLMConfig defines model for LLMConfig.
type LLMConfig struct {
	ApiKey  string `json:"api_key"`
	BaseUrl string `json:"base_url"`
	Model   string `json:"model"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Ctx   *map[string]interface{}    `json:"ctx,omitempty"`
	Input interface{}                `json:"input,omitempty"`
	Loc   []ValidationError_Loc_Item `json:"loc"`
	Msg   string                     `json:"msg"`
	Type  string                     `json:"type"`
}

// ValidationErrorLoc0 defines model for .
type ValidationErrorLoc0 = string

// ValidationErrorLoc1 defines model for .
type ValidationErrorLoc1 = int

// ValidationError_Loc_Item defines model for ValidationError.loc.Item.
type ValidationError_Loc_Item struct {
	union json.RawMessage
}

// VoiceConfig defines model for VoiceConfig.
type VoiceConfig struct {
	Stt           *string `json:"stt,omitempty"`
	Tts           *string `json:"tts,omitempty"`
	TurnDetection *string `json:"turn_detection,omitempty"`
	Vad           *string `json:"vad,omitempty"`
}

// ListCallsCallsGetParams defines parameters for ListCallsCallsGet.
type ListCallsCallsGetParams struct {
	Cursor        *string                        `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit         *int                           `form:"limit,omitempty" json:"limit,omitempty"`
	Status        *ListCallsCallsGetParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	To            *string                        `form:"to,omitempty" json:"to,omitempty"`
	Authorization *string                        `json:"authorization,omitempty"`
}

// ListCallsCallsGetParamsStatus defines parameters for ListCallsCallsGet.
type ListCallsCallsGetParamsStatus string

// CreateCallCallsPostParams defines parameters for CreateCallCallsPost.
type CreateCallCallsPostParams struct {
	Authorization  *string `json:"authorization,omitempty"`
	IdempotencyKey *string `json:"Idempotency-Key,omitempty"`
}

// GetCallCallsCallIdGetParams defines parameters for GetCallCallsCallIdGet.
type GetCallCallsCallIdGetParams struct {
	Authorization *string `json:"authorization,omitempty"`
}

// ListEventsEventsGetParams defines parameters for ListEventsEventsGet.
type ListEventsEventsGetParams struct {
	Cursor        *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit         *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Id            *string `form:"id,omitempty" json:"id,omitempty"`
	Kind          *string `form:"kind,omitempty" json:"kind,omitempty"`
	Authorization *string `json:"authorization,omitempty"`
}

// CreateCallCallsPostJSONRequestBody defines body for CreateCallCallsPost for application/json ContentType.
type CreateCallCallsPostJSONRequestBody = CallCreate

// AsValidationErrorLoc0 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc0
func (t ValidationError_Loc_Item) AsValidationErrorLoc0() (ValidationErrorLoc0, error) {
	var body ValidationErrorLoc0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc0 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) FromValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc0 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsValidationErrorLoc1 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc1
func (t ValidationError_Loc_Item) AsValidationErrorLoc1() (ValidationErrorLoc1, error) {
	var body ValidationErrorLoc1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc1 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) FromValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc1 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ValidationError_Loc_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ValidationError_Loc_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListCallsCallsGet request
	ListCallsCallsGet(ctx context.Context, params *ListCallsCallsGetParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateCallCallsPostWithBody request with any body
	CreateCallCallsPostWithBody(ctx context.Context, params *CreateCallCallsPostParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateCallCallsPost(ctx context.Context, params *CreateCallCallsPostParams, body CreateCallCallsPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCallCallsCallIdGet request
	GetCallCallsCallIdGet(ctx context.Context, callId openapi_types.UUID, params *GetCallCallsCallIdGetParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListEventsEventsGet request
	ListEventsEventsGet(ctx context.Context, params *ListEventsEventsGetParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// HealthzHealthzGet request
	HealthzHealthzGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListCallsCallsGet(ctx context.Context, params *ListCallsCallsGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListCallsCallsGetRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateCallCallsPostWithBody(ctx context.Context, params *CreateCallCallsPostParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateCallCallsPostRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateCallCallsPost(ctx context.Context, params *CreateCallCallsPostParams, body CreateCallCallsPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateCallCallsPostRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCallCallsCallIdGet(ctx context.Context, callId openapi_types.UUID, params *GetCallCallsCallIdGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCallCallsCallIdGetRequest(c.Server, callId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListEventsEventsGet(ctx context.Context, params *ListEventsEventsGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListEventsEventsGetRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) HealthzHealthzGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHealthzHealthzGetRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListCallsCallsGetRequest generates requests for ListCallsCallsGet
func NewListCallsCallsGetRequest(server string, params *ListCallsCallsGetParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/calls")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "cursor", *params.Cursor, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Status != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "status", *params.Status, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.To != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "to", *params.To, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.Authorization != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "authorization", *params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("authorization", headerParam0)
		}

	}

	return req, nil
}

// NewCreateCallCallsPostRequest calls the generic CreateCallCallsPost builder with application/json body
func NewCreateCallCallsPostRequest(server string, params *CreateCallCallsPostParams, body CreateCallCallsPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateCallCallsPostRequestWithBody(server, params, "application/json", bodyReader)
}

// NewCreateCallCallsPostRequestWithBody generates requests for CreateCallCallsPost with any type of body
func NewCreateCallCallsPostRequestWithBody(server string, params *CreateCallCallsPostParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/calls")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.Authorization != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "authorization", *params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("authorization", headerParam0)
		}

		if params.IdempotencyKey != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithOptions("simple", false, "Idempotency-Key", *params.IdempotencyKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Idempotency-Key", headerParam1)
		}

	}

	return req, nil
}

// NewGetCallCallsCallIdGetRequest generates requests for GetCallCallsCallIdGet
func NewGetCallCallsCallIdGetRequest(server string, callId openapi_types.UUID, params *GetCallCallsCallIdGetParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "call_id", callId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/calls/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.Authorization != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "authorization", *params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("authorization", headerParam0)
		}

	}

	return req, nil
}

// NewListEventsEventsGetRequest generates requests for ListEventsEventsGet
func NewListEventsEventsGetRequest(server string, params *ListEventsEventsGetParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/events")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "cursor", *params.Cursor, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Id != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "id", *params.Id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Kind != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "kind", *params.Kind, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.Authorization != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "authorization", *params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("authorization", headerParam0)
		}

	}

	return req, nil
}

// NewHealthzHealthzGetRequest generates requests for HealthzHealthzGet
func NewHealthzHealthzGetRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/healthz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListCallsCallsGetWithResponse request
	ListCallsCallsGetWithResponse(ctx context.Context, params *ListCallsCallsGetParams, reqEditors ...RequestEditorFn) (*ListCallsCallsGetResponse, error)

	// CreateCallCallsPostWithBodyWithResponse request with any body
	CreateCallCallsPostWithBodyWithResponse(ctx context.Context, params *CreateCallCallsPostParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateCallCallsPostResponse, error)

	CreateCallCallsPostWithResponse(ctx context.Context, params *CreateCallCallsPostParams, body CreateCallCallsPostJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateCallCallsPostResponse, error)

	// GetCallCallsCallIdGetWithResponse request
	GetCallCallsCallIdGetWithResponse(ctx context.Context, callId openapi_types.UUID, params *GetCallCallsCallIdGetParams, reqEditors ...RequestEditorFn) (*GetCallCallsCallIdGetResponse, error)

	// ListEventsEventsGetWithResponse request
	ListEventsEventsGetWithResponse(ctx context.Context, params *ListEventsEventsGetParams, reqEditors ...RequestEditorFn) (*ListEventsEventsGetResponse, error)

	// HealthzHealthzGetWithResponse request
	HealthzHealthzGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthzHealthzGetResponse, error)
}

type ListCallsCallsGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CallListResponse
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r ListCallsCallsGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListCallsCallsGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateCallCallsPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *CallResponse
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r CreateCallCallsPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateCallCallsPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetCallCallsCallIdGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CallResponse
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r GetCallCallsCallIdGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCallCallsCallIdGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListEventsEventsGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EventStreamResponse
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r ListEventsEventsGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListEventsEventsGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type HealthzHealthzGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *map[string]string
}

// Status returns HTTPResponse.Status
func (r HealthzHealthzGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HealthzHealthzGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListCallsCallsGetWithResponse request returning *ListCallsCallsGetResponse
func (c *ClientWithResponses) ListCallsCallsGetWithResponse(ctx context.Context, params *ListCallsCallsGetParams, reqEditors ...RequestEditorFn) (*ListCallsCallsGetResponse, error) {
	rsp, err := c.ListCallsCallsGet(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListCallsCallsGetResponse(rsp)
}

// CreateCallCallsPostWithBodyWithResponse request with arbitrary body returning *CreateCallCallsPostResponse
func (c *ClientWithResponses) CreateCallCallsPostWithBodyWithResponse(ctx context.Context, params *CreateCallCallsPostParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateCallCallsPostResponse, error) {
	rsp, err := c.CreateCallCallsPostWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateCallCallsPostResponse(rsp)
}

func (c *ClientWithResponses) CreateCallCallsPostWithResponse(ctx context.Context, params *CreateCallCallsPostParams, body CreateCallCallsPostJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateCallCallsPostResponse, error) {
	rsp, err := c.CreateCallCallsPost(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateCallCallsPostResponse(rsp)
}

// GetCallCallsCallIdGetWithResponse request returning *GetCallCallsCallIdGetResponse
func (c *ClientWithResponses) GetCallCallsCallIdGetWithResponse(ctx context.Context, callId openapi_types.UUID, params *GetCallCallsCallIdGetParams, reqEditors ...RequestEditorFn) (*GetCallCallsCallIdGetResponse, error) {
	rsp, err := c.GetCallCallsCallIdGet(ctx, callId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCallCallsCallIdGetResponse(rsp)
}

// ListEventsEventsGetWithResponse request returning *ListEventsEventsGetResponse
func (c *ClientWithResponses) ListEventsEventsGetWithResponse(ctx context.Context, params *ListEventsEventsGetParams, reqEditors ...RequestEditorFn) (*ListEventsEventsGetResponse, error) {
	rsp, err := c.ListEventsEventsGet(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListEventsEventsGetResponse(rsp)
}

// HealthzHealthzGetWithResponse request returning *HealthzHealthzGetResponse
func (c *ClientWithResponses) HealthzHealthzGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthzHealthzGetResponse, error) {
	rsp, err := c.HealthzHealthzGet(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHealthzHealthzGetResponse(rsp)
}

// ParseListCallsCallsGetResponse parses an HTTP response from a ListCallsCallsGetWithResponse call
func ParseListCallsCallsGetResponse(rsp *http.Response) (*ListCallsCallsGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListCallsCallsGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CallListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseCreateCallCallsPostResponse parses an HTTP response from a CreateCallCallsPostWithResponse call
func ParseCreateCallCallsPostResponse(rsp *http.Response) (*CreateCallCallsPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateCallCallsPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest CallResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetCallCallsCallIdGetResponse parses an HTTP response from a GetCallCallsCallIdGetWithResponse call
func ParseGetCallCallsCallIdGetResponse(rsp *http.Response) (*GetCallCallsCallIdGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCallCallsCallIdGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CallResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseListEventsEventsGetResponse parses an HTTP response from a ListEventsEventsGetWithResponse call
func ParseListEventsEventsGetResponse(rsp *http.Response) (*ListEventsEventsGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListEventsEventsGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EventStreamResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseHealthzHealthzGetResponse parses an HTTP response from a HealthzHealthzGetWithResponse call
func ParseHealthzHealthzGetResponse(rsp *http.Response) (*HealthzHealthzGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HealthzHealthzGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest map[string]string
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
